# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: nd-spring-boot-demo
  nd-spring-boot-demo:
    build:
      context: .
    environment:
      SERVER_PORT: 777
      spring.datasource.url: jdbc:postgresql://db:5432/nd-spring-boot-demo
      spring.datasource.username: postgres
      spring.datasource.password: 123123
    ports:
      - 777:777
    depends_on:
      - db
    restart: always